# CISC7204 Suggested Exercise 05 — Practice 01 — Weather Data

LU MENGJIE · MC643920

Questions follow the supplied Moodle exercise. Each code cell was executed against the supplied CSV. Large results show a preview, while the full filtered DataFrame is retained in the named variable.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

source = Path('../Datasets') / '1. Weather Data.csv'
df = pd.read_csv(source)
print('Source:', source, '| rows:', len(df), '| columns:', len(df.columns))
display(df.head(3))

Source: ..\Datasets\1. Weather Data.csv | rows: 8784 | columns: 8

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"

In [2]:
df = df.rename(columns={'Weather': 'Weather Condition'})
print('Renamed column Weather → Weather Condition')

Renamed column Weather → Weather Condition

### Question 1.1: Unique wind speeds

In [3]:
print('Unique wind speeds (km/h):', sorted(df['Wind Speed_km/h'].dropna().unique()))
print('Number of unique values:', df['Wind Speed_km/h'].nunique())

Unique wind speeds (km/h): [np.int64(0), np.int64(2), np.int64(4), np.int64(6), np.int64(7), np.int64(9), np.int64(11), np.int64(13), np.int64(15), np.int64(17), np.int64(19), np.int64(20), np.int64(22), np.int64(24), np.int64(26), np.int64(28), np.int64(30), np.int64(32), np.int64(33), np.int64(35), np.int64(37), np.int64(39), np.int64(41), np.int64(43), np.int64(44), np.int64(46), np.int64(48), np.int64(50), np.int64(52), np.int64(54), np.int64(57), np.int64(63), np.int64(70), np.int64(83)]
Number of unique values: 34

### Question 1.2: How many times was the weather exactly Clear?

In [4]:
clear = df[df['Weather Condition'].eq('Clear')]
print('Clear records:', len(clear))
display(clear.head(10))

Clear records: 1326

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
241,1/11/2012 1:00,-10.7,-17.8,56,17,25.0,101.49,Clear
242,1/11/2012 2:00,-12.0,-18.9,56,19,25.0,101.57,Clear
243,1/11/2012 3:00,-12.7,-19.4,57,19,25.0,101.64,Clear
244,1/11/2012 4:00,-13.4,-20.1,57,17,25.0,101.66,Clear
344,1/15/2012 8:00,-23.3,-28.5,62,7,24.1,102.45,Clear

### Question 1.3: Wind speed equal to 4 km/h

In [5]:
wind4 = df[df['Wind Speed_km/h'].eq(4)]
print('Records with wind speed 4 km/h:', len(wind4))
display(wind4.head(10))

Records with wind speed 4 km/h: 474

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
147,1/7/2012 3:00,-7.8,-10.8,79,4,19.3,100.12,Cloudy
149,1/7/2012 5:00,-6.9,-9.7,80,4,19.3,100.12,Cloudy
164,1/7/2012 20:00,-1.8,-3.7,87,4,9.7,100.48,Snow
166,1/7/2012 22:00,-1.5,-3.0,89,4,4.0,100.54,Fog
194,1/9/2012 2:00,-9.0,-14.1,66,4,25.0,102.15,Mostly Cloudy

### Question 1.4: Null values in each column

In [6]:
display(df.isna().sum().rename('missing_values').to_frame())

                   missing_values
Date/Time                       0
Temp_C                          0
Dew Point Temp_C                0
Rel Hum_%                       0
Wind Speed_km/h                 0
Visibility_km                   0
Press_kPa                       0
Weather Condition               0

### Question 1.5: Rename Weather to Weather Condition

In [7]:
print('Column name after rename:', 'Weather Condition' if 'Weather Condition' in df.columns else 'NOT FOUND')
print('All columns:', df.columns.tolist())

Column name after rename: Weather Condition
All columns: ['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%', 'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather Condition']

### Question 1.6: Mean visibility

In [8]:
print('Mean visibility (km):', df['Visibility_km'].mean())

Mean visibility (km): 27.664446721311474

### Question 1.7: Standard deviation of pressure

In [9]:
print('Sample standard deviation of pressure (kPa):', df['Press_kPa'].std())

Sample standard deviation of pressure (kPa): 0.8440047459486483

### Question 1.8: Variance of relative humidity

In [10]:
print('Sample variance of relative humidity:', df['Rel Hum_%'].var())

Sample variance of relative humidity: 286.24855019850196

### Question 1.9: All records containing Snow

In [11]:
snow = df[df['Weather Condition'].str.contains('Snow', case=False, na=False)]
print('Snow-related records:', len(snow))
display(snow.head(12))

Snow-related records: 583

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
41,1/2/2012 17:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,1/2/2012 20:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,1/2/2012 23:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
50,1/3/2012 2:00,-10.5,-15.8,65,22,12.9,100.53,Snow Showers
51,1/3/2012 3:00,-11.3,-18.7,54,33,25.0,100.61,Snow Showers
53,1/3/2012 5:00,-12.9,-19.1,60,22,25.0,100.76,Snow Showers
54,1/3/2012 6:00,-13.3,-19.3,61,19,25.0,100.85,Snow Showers
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow

### Question 1.10: Wind speed above 24 km/h and visibility 25 km

In [12]:
q = df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km'] == 25)]
print('Matching records:', len(q))
display(q.head(12))

Matching records: 308

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
28,1/2/2012 4:00,2.9,-2.3,69,32,25.0,99.26,Mostly Cloudy
29,1/2/2012 5:00,2.6,-2.3,70,32,25.0,99.21,Mostly Cloudy
30,1/2/2012 6:00,2.3,-2.6,70,26,25.0,99.18,Mostly Cloudy
31,1/2/2012 7:00,2.0,-2.9,70,33,25.0,99.14,Mostly Cloudy
42,1/2/2012 18:00,-4.1,-11.4,57,28,25.0,99.86,Mostly Cloudy
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers

### Question 1.11: Mean numeric values by weather condition

In [13]:
display(df.groupby('Weather Condition').mean(numeric_only=True).round(2))

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,
Clear,6.83,0.09,64.50,10.56,30.15,101.59
Cloudy,7.97,2.38,69.59,16.13,26.63,100.91
Drizzle,7.35,5.50,88.24,16.10,17.93,100.44
"Drizzle,Fog",8.07,7.03,93.28,11.86,5.26,100.79
"Drizzle,Ice Pellets,Fog",0.40,-0.70,92.00,20.00,4.00,100.79
"Drizzle,Snow",1.05,0.15,93.50,14.00,10.50,100.89
"Drizzle,Snow,Fog",0.69,0.12,95.87,15.53,5.51,99.28
Fog,4.30,3.16,92.29,7.95,6.25,101.18
Freezing Drizzle,-5.66,-8.00,83.57,16.57,9.20,100.20
"Freezing Drizzle,Fog",-2.53,-4.18,88.50,17.00,5.27,100.44
"Freezing Drizzle,Haze",-5.43,-8.00,82.00,10.33,2.67,100.32
"Freezing Drizzle,Snow",-5.11,-7.07,86.09,16.27,5.87,100.52
Freezing Fog,-7.58,-9.25,87.75,4.75,0.65,102.32
Freezing Rain,-3.89,-6.08,84.64,19.21,8.24,99.65
"Freezing Rain,Fog",-2.22,-3.75,89.50,15.50,7.55,99.94
"Freezing Rain,Haze",-4.90,-7.45,82.50,7.50,2.40,100.38
"Freezing Rain,Ice Pellets,Fog",-2.60,-3.70,92.00,28.00,8.00,100.95
"Freezing Rain,Snow Grains",-5.00,-7.30,84.00,32.00,4.80,98.56
Haze,-0.20,-2.98,81.62,10.44,7.83,101.48
Mainly Clear,12.56,4.58,60.67,14.14,34.26,101.25
"Moderate Rain,Fog",1.70,0.80,94.00,17.00,6.40,99.98
Moderate Snow,-5.52,-7.25,87.75,33.75,0.75,100.28
"Moderate Snow,Blowing Snow",-5.45,-6.50,92.50,40.00,0.60,100.57
Mostly Cloudy,10.57,3.13,62.10,15.81,31.25,101.03
Rain,9.79,7.04,83.62,19.25,18.86,100.23
Rain Showers,13.72,9.19,75.16,17.13,22.82,100.40
"Rain Showers,Fog",12.80,12.10,96.00,13.00,6.40,99.83
"Rain Showers,Snow Showers",2.15,-1.50,76.50,22.50,21.70,101.10
"Rain,Fog",8.27,7.22,93.19,14.79,6.87,100.50
"Rain,Haze",4.63,2.07,83.33,11.67,6.70,100.54
"Rain,Ice Pellets",0.60,-0.60,92.00,24.00,9.70,100.12
"Rain,Snow",1.06,-0.57,89.00,28.39,11.67,99.95
"Rain,Snow Grains",1.90,-2.10,75.00,26.00,25.00,100.60
"Rain,Snow,Fog",0.80,0.30,96.00,9.00,6.40,100.73
"Rain,Snow,Ice Pellets",1.10,-0.18,91.50,23.25,6.00,100.10
Snow,-4.52,-7.62,79.31,20.04,11.17,100.54
Snow Pellets,0.70,-6.40,59.00,35.00,2.40,99.70
Snow Showers,-3.51,-7.87,72.35,19.23,20.16,100.96
"Snow Showers,Fog",-10.68,-11.90,90.75,13.75,7.02,101.29
"Snow,Blowing Snow",-5.41,-7.62,84.47,34.84,4.11,99.70
"Snow,Fog",-5.08,-6.36,90.68,17.32,4.54,100.69
"Snow,Haze",-4.02,-6.86,80.60,5.00,4.64,100.78
"Snow,Ice Pellets",-1.88,-3.67,87.67,23.83,7.42,100.55
Thunderstorms,24.15,19.75,77.00,7.50,24.55,100.23
"Thunderstorms,Heavy Rain Showers",10.90,9.00,88.00,9.00,2.40,100.26
"Thunderstorms,Moderate Rain Showers,Fog",19.60,18.50,93.00,15.00,3.20,100.01
"Thunderstorms,Rain",20.43,18.53,89.00,15.67,19.83,100.42
"Thunderstorms,Rain Showers",20.04,17.62,86.38,18.31,15.89,100.23
"Thunderstorms,Rain Showers,Fog",21.60,18.70,84.00,19.67,9.70,100.06
"Thunderstorms,Rain,Fog",20.60,18.60,88.00,19.00,4.80,100.08

### Question 1.12: Minimum and maximum numeric values by weather condition

In [14]:
extremes = df.groupby('Weather Condition').agg(['min', 'max'])
display(extremes)

                                                Date/Time                    \
                                                      min               max
Weather Condition
Clear                                      1/11/2012 1:00     9/9/2012 5:00
Cloudy                                     1/1/2012 17:00    9/9/2012 23:00
Drizzle                                   1/23/2012 21:00    9/30/2012 3:00
Drizzle,Fog                               1/23/2012 20:00    9/30/2012 2:00
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00   12/17/2012 9:00
Drizzle,Snow                             12/17/2012 15:00  12/19/2012 18:00
Drizzle,Snow,Fog                         12/18/2012 21:00   12/22/2012 3:00
Fog                                         1/1/2012 0:00    9/22/2012 0:00
Freezing Drizzle                          1/13/2012 10:00     2/1/2012 5:00
Freezing Drizzle,Fog                        1/1/2012 2:00   12/10/2012 5:00
Freezing Drizzle,Haze                      2/1/2012 11:00    2/1/2012 13:00
Freezing Drizzle,Snow                      1/13/2012 3:00    3/2/2012 12:00
Freezing Fog                               1/22/2012 6:00    3/17/2012 6:00
Freezing Rain                             1/13/2012 11:00     2/1/2012 7:00
Freezing Rain,Fog                         1/17/2012 23:00   12/17/2012 1:00
Freezing Rain,Haze                         2/1/2012 14:00    2/1/2012 15:00
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00   12/17/2012 3:00
Freezing Rain,Snow Grains                  1/13/2012 9:00    1/13/2012 9:00
Haze                                      1/22/2012 12:00   3/13/2012 23:00
Mainly Clear                              1/10/2012 11:00     9/9/2012 9:00
Moderate Rain,Fog                         12/10/2012 8:00   12/10/2012 8:00
Moderate Snow                             1/12/2012 15:00   12/27/2012 9:00
Moderate Snow,Blowing Snow               12/27/2012 10:00  12/27/2012 12:00
Mostly Cloudy                              1/1/2012 16:00     9/9/2012 2:00
Rain                                       1/1/2012 18:00     9/5/2012 2:00
Rain Showers                               1/1/2012 22:00    9/8/2012 16:00
Rain Showers,Fog                          10/20/2012 3:00   10/20/2012 3:00
Rain Showers,Snow Showers                  11/4/2012 8:00   12/5/2012 10:00
Rain,Fog                                  1/23/2012 18:00   9/30/2012 23:00
Rain,Haze                                  3/13/2012 7:00    3/13/2012 9:00
Rain,Ice Pellets                          12/18/2012 5:00   12/18/2012 5:00
Rain,Snow                                  1/10/2012 5:00    4/23/2012 3:00
Rain,Snow Grains                          12/21/2012 0:00   12/21/2012 0:00
Rain,Snow,Fog                             12/8/2012 21:00   12/8/2012 21:00
Rain,Snow,Ice Pellets                     12/21/2012 1:00   12/21/2012 5:00
Snow                                       1/10/2012 1:00    4/27/2012 9:00
Snow Pellets                             11/24/2012 15:00  11/24/2012 15:00
Snow Showers                               1/12/2012 7:00    3/4/2012 21:00
Snow Showers,Fog                          12/26/2012 9:00  12/29/2012 13:00
Snow,Blowing Snow                         1/13/2012 21:00    2/25/2012 9:00
Snow,Fog                                 12/16/2012 15:00   3/14/2012 19:00
Snow,Haze                                  2/1/2012 17:00    2/1/2012 21:00
Snow,Ice Pellets                          12/10/2012 3:00     3/3/2012 4:00
Thunderstorms                              7/16/2012 1:00    7/4/2012 16:00
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00    5/29/2012 6:00
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00    7/17/2012 6:00
Thunderstorms,Rain                        5/25/2012 20:00   7/23/2012 18:00
Thunderstorms,Rain Showers                5/29/2012 16:00     9/8/2012 4:00
Thunderstorms,Rain Showers,Fog             6/29/2012 3:00   7/31/2012 20:00
Thunderstorms,Rain,Fog                     7/17/2012 5:00    7/17/2012 5:00

                                        Temp_C       Dew Point Temp_C        \
                                           min   max              min   max
Weather Condition
Clear                                    -23.3  32.8            -28.5  20.4
Cloudy                                   -21.4  30.5            -26.8  22.6
Drizzle                                    1.1  18.8             -0.2  17.7
Drizzle,Fog                                0.0  19.9             -1.6  19.1
Drizzle,Ice Pellets,Fog                    0.4   0.4             -0.7  -0.7
Drizzle,Snow                               0.9   1.2              0.1   0.2
Drizzle,Snow,Fog                           0.3   1.1             -0.1   0.6
Fog                                      -16.0  20.8            -17.2  19.6
Freezing Drizzle                          -9.0  -2.3            -12.2  -3.3
Freezing Drizzle,Fog                      -6.4  -0.3             -9.0  -2.3
Freezing Drizzle,Haze                     -5.8  -5.0             -8.3  -7.7
Freezing Drizzle,Snow                     -8.3  -3.3            -10.4  -4.6
Freezing Fog                             -19.0  -0.1            -22.9  -0.3
Freezing Rain                             -6.5   0.3             -9.0  -1.7
Freezing Rain,Fog                         -6.1   0.1             -8.7  -0.9
Freezing Rain,Haze                        -4.9  -4.9             -7.5  -7.4
Freezing Rain,Ice Pellets,Fog             -2.6  -2.6             -3.7  -3.7
Freezing Rain,Snow Grains                 -5.0  -5.0             -7.3  -7.3
Haze                                     -11.5  14.1            -16.0  11.1
Mainly Clear                             -22.8  33.0            -28.0  21.2
Moderate Rain,Fog                          1.7   1.7              0.8   0.8
Moderate Snow                             -6.3  -4.9             -7.6  -6.7
Moderate Snow,Blowing Snow                -5.5  -5.4             -6.6  -6.4
Mostly Cloudy                            -23.2  32.4            -28.5  24.4
Rain                                       0.3  22.8             -5.7  20.4
Rain Showers                               1.6  26.4             -7.2  23.0
Rain Showers,Fog                          12.8  12.8             12.1  12.1
Rain Showers,Snow Showers                  2.1   2.2             -1.8  -1.2
Rain,Fog                                   0.0  21.7             -1.2  19.5
Rain,Haze                                  4.0   5.5              1.0   2.9
Rain,Ice Pellets                           0.6   0.6             -0.6  -0.6
Rain,Snow                                  0.6   1.7             -1.7   0.5
Rain,Snow Grains                           1.9   1.9             -2.1  -2.1
Rain,Snow,Fog                              0.8   0.8              0.3   0.3
Rain,Snow,Ice Pellets                      0.9   1.3             -0.7   0.1
Snow                                     -16.7   3.7            -24.6   0.3
Snow Pellets                               0.7   0.7             -6.4  -6.4
Snow Showers                             -13.3   2.9            -19.3  -0.7
Snow Showers,Fog                         -11.3 -10.0            -12.7 -11.1
Snow,Blowing Snow                        -12.0  -1.4            -16.2  -2.9
Snow,Fog                                 -10.1   1.1            -12.0   0.8
Snow,Haze                                 -4.3  -3.6             -7.2  -6.4
Snow,Ice Pellets                          -4.3   0.8             -5.9  -1.7
Thunderstorms                             21.6  26.7             19.4  20.1
Thunderstorms,Heavy Rain Showers          10.9  10.9              9.0   9.0
Thunderstorms,Moderate Rain Showers,Fog   19.6  19.6             18.5  18.5
Thunderstorms,Rain                        19.4  21.3             18.2  19.1
Thunderstorms,Rain Showers                11.0  25.5              7.0  23.1
Thunderstorms,Rain Showers,Fog            19.5  22.9             16.1  21.3
Thunderstorms,Rain,Fog                    20.6  20.6             18.6  18.6

                                        Rel Hum_%      Wind Speed_km/h      \
                                              min  max             min max
Weather Condition
Clear                                          20   99               0  33
Cloudy                                         18   99               0  54
Drizzle                                        74   96               0  30
Drizzle,Fog                                    85  100               0  28
Drizzle,Ice Pellets,Fog                        92   92              20  20
Drizzle,Snow                                   92   95               9  19
Drizzle,Snow,Fog                               92   98               7  32
Fog                                            80  100               0  22
Freezing Drizzle                               78   93               6  26
Freezing Drizzle,Fog                           82   94               6  33
Freezing Drizzle,Haze                          81   83               9  11
Freezing Drizzle,Snow                          79   94               6  24
Freezing Fog                                   71   99               0   9
Freezing Rain                                  81   92               7  28
Freezing Rain,Fog                              82   93               7  26
Freezing Rain,Haze                             82   83               6   9
Freezing Rain,Ice Pellets,Fog                  92   92              28  28
Freezing Rain,Snow Grains                      84   84              32  32
Haze                                           68   86               0  17
Mainly Clear                                   20   99               0  63
Moderate Rain,Fog                              94   94              17  17
Moderate Snow                                  83   93              26  39
Moderate Snow,Blowing Snow                     92   93              39  41
Mostly Cloudy                                  18  100               0  83
Rain                                           40   99               0  52
Rain Showers                                   37   97               0  41
Rain Showers,Fog                               96   96              13  13
Rain Showers,Snow Showers                      75   78              17  28
Rain,Fog                                       83  100               0  46
Rain,Haze                                      81   86               7  17
Rain,Ice Pellets                               92   92              24  24
Rain,Snow                                      81   94              13  52
Rain,Snow Grains                               75   75              26  26
Rain,Snow,Fog                                  96   96               9   9
Rain,Snow,Ice Pellets                          88   94              17  28
Snow                                           41   96               0  57
Snow Pellets                                   59   59              35  35
Snow Showers                                   52   94               0  37
Snow Showers,Fog                               89   92               7  22
Snow,Blowing Snow                              70   91              24  48
Snow,Fog                                       77   99               4  35
Snow,Haze                                      80   81               0  15
Snow,Ice Pellets                               76   92              19  33
Thunderstorms                                  67   87               0  15
Thunderstorms,Heavy Rain Showers               88   88               9   9
Thunderstorms,Moderate Rain Showers,Fog        93   93              15  15
Thunderstorms,Rain                             83   93               4  30
Thunderstorms,Rain Showers                     68   98               7  32
Thunderstorms,Rain Showers,Fog                 80   91               7  35
Thunderstorms,Rain,Fog                         88   88              19  19

                                        Visibility_km       Press_kPa
                                                  min   max       min     max
Weather Condition
Clear                                            11.3  48.3     99.52  103.63
Cloudy                                           11.3  48.3     98.39  103.65
Drizzle                                           6.4  25.0     97.84  101.56
Drizzle,Fog                                       1.0   9.7     98.65  102.07
Drizzle,Ice Pellets,Fog                           4.0   4.0    100.79  100.79
Drizzle,Snow                                      9.7  11.3    100.63  101.15
Drizzle,Snow,Fog                                  2.4   9.7     97.79  100.15
Fog                                               0.2   9.7     98.31  103.04
Freezing Drizzle                                  4.8  12.9     98.44  101.02
Freezing Drizzle,Fog                              3.6   8.0     98.74  101.27
Freezing Drizzle,Haze                             2.0   4.0    100.28  100.36
Freezing Drizzle,Snow                             2.4  12.9     99.19  101.18
Freezing Fog                                      0.2   0.8    101.97  102.85
Freezing Rain                                     2.8  16.1     98.22  101.00
Freezing Rain,Fog                                 2.8   9.7     98.32  101.01
Freezing Rain,Haze                                2.0   2.8    100.34  100.41
Freezing Rain,Ice Pellets,Fog                     8.0   8.0    100.95  100.95
Freezing Rain,Snow Grains                         4.8   4.8     98.56   98.56
Haze                                              4.8   9.7    100.35  102.97
Mainly Clear                                     12.9  48.3     98.67  103.59
Moderate Rain,Fog                                 6.4   6.4     99.98   99.98
Moderate Snow                                     0.6   0.8     99.88  100.67
Moderate Snow,Blowing Snow                        0.6   0.6    100.50  100.64
Mostly Cloudy                                    11.3  48.3     98.36  103.65
Rain                                              4.0  48.3     97.52  102.26
Rain Showers                                      6.4  48.3     98.51  102.31
Rain Showers,Fog                                  6.4   6.4     99.83   99.83
Rain Showers,Snow Showers                        19.3  24.1    101.09  101.11
Rain,Fog                                          2.0   9.7     98.61  101.77
Rain,Haze                                         4.0   9.7    100.50  100.61
Rain,Ice Pellets                                  9.7   9.7    100.12  100.12
Rain,Snow                                         2.4  25.0     98.18  101.07
Rain,Snow Grains                                 25.0  25.0    100.60  100.60
Rain,Snow,Fog                                     6.4   6.4    100.73  100.73
Rain,Snow,Ice Pellets                             4.8   6.4     99.85  100.47
Snow                                              1.0  25.0     97.75  102.73
Snow Pellets                                      2.4   2.4     99.70   99.70
Snow Showers                                      2.4  48.3     99.49  102.50
Snow Showers,Fog                                  4.0   9.7    100.63  102.52
Snow,Blowing Snow                                 0.6   9.7     98.11  100.62
Snow,Fog                                          1.2   9.7     99.38  102.07
Snow,Haze                                         4.0   6.4    100.61  100.99
Snow,Ice Pellets                                  2.8  11.3     99.40  100.96
Thunderstorms                                    24.1  25.0     99.84  100.62
Thunderstorms,Heavy Rain Showers                  2.4   2.4    100.26  100.26
Thunderstorms,Moderate Rain Showers,Fog           3.2   3.2    100.01  100.01
Thunderstorms,Rain                               16.1  24.1    100.19  100.83
Thunderstorms,Rain Showers                        6.4  25.0     99.65  101.06
Thunderstorms,Rain Showers,Fog                    9.7   9.7     99.71  100.64
Thunderstorms,Rain,Fog                            4.8   4.8    100.08  100.08

### Question 1.13: Records where condition is exactly Fog

In [15]:
fog = df[df['Weather Condition'].eq('Fog')]
print('Fog records:', len(fog))
display(fog.head(12))

Fog records: 150

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,1/1/2012 7:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,1/1/2012 8:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,1/1/2012 9:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,1/1/2012 10:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,1/1/2012 11:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,1/1/2012 12:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,1/1/2012 13:00,0.2,-1.7,87,13,4.8,100.58,Fog

### Question 1.14: Clear OR visibility above 40 km

In [16]:
q = df[df['Weather Condition'].eq('Clear') | (df['Visibility_km'] > 40)]
print('Matching records:', len(q))
display(q.head(12))

Matching records: 3027

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
111,1/5/2012 15:00,-4.3,-12.0,55,26,48.3,100.52,Mainly Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
183,1/8/2012 15:00,-6.6,-12.9,61,20,48.3,102.04,Mostly Cloudy

### Question 1.15: (Clear AND humidity above 50%) OR visibility above 40 km

In [17]:
q = df[(df['Weather Condition'].eq('Clear') & (df['Rel Hum_%'] > 50)) | (df['Visibility_km'] > 40)]
print('Matching records:', len(q))
display(q.head(12))

Matching records: 2921

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
111,1/5/2012 15:00,-4.3,-12.0,55,26,48.3,100.52,Mainly Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
183,1/8/2012 15:00,-6.6,-12.9,61,20,48.3,102.04,Mostly Cloudy
241,1/11/2012 1:00,-10.7,-17.8,56,17,25.0,101.49,Clear