# CISC7204 Suggested Exercise 05 — Practice 04 — COVID-19 Data

LU MENGJIE · MC643920

Questions follow the supplied Moodle exercise. Each code cell was executed against the supplied CSV. Large results show a preview, while the full filtered DataFrame is retained in the named variable.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

source = Path('../Datasets') / '4. Covid_19_data.csv'
df = pd.read_csv(source)
print('Source:', source, '| rows:', len(df), '| columns:', len(df.columns))
display(df.head(3))

Source: ..\Datasets\4. Covid_19_data.csv | rows: 321 | columns: 6

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702

### Question 4.1: Confirmed, deaths and recovered by region

In [2]:
region_totals = df.groupby('Region')[['Confirmed','Deaths','Recovered']].sum()
display(region_totals)

                    Confirmed  Deaths  Recovered
Region
Afghanistan              1939      60        252
Albania                   766      30        455
Algeria                  3848     444       1702
Andorra                   743      42        423
Angola                     27       2          7
...                       ...     ...        ...
West Bank and Gaza        344       2         71
Western Sahara              6       0          5
Yemen                       6       0          1
Zambia                     97       3         54
Zimbabwe                   32       4          5

[187 rows x 3 columns]

### Question 4.2: Remove records with fewer than 10 confirmed cases

In [3]:
before = len(df)
df = df[df['Confirmed'] >= 10].copy()
print('Removed:', before - len(df), 'Remaining:', len(df))
print('Minimum Confirmed remaining:', df['Confirmed'].min())

Removed: 17 Remaining: 304
Minimum Confirmed remaining: 10

### Question 4.3: Region with the highest confirmed total

In [4]:
region_totals = df.groupby('Region')['Confirmed'].sum()
maximum = region_totals.max()
display(region_totals[region_totals.eq(maximum)].to_frame('Confirmed_total'))

        Confirmed_total
Region
US              1039909

### Question 4.4: Region with the lowest death total

In [5]:
death_totals = df.groupby('Region')['Deaths'].sum()
minimum = death_totals.min()
print('Minimum deaths:', minimum)
display(death_totals[death_totals.eq(minimum)].to_frame('Deaths_total'))

Minimum deaths: 0

                                  Deaths_total
Region
Cambodia                                     0
Central African Republic                     0
Dominica                                     0
Eritrea                                      0
Fiji                                         0
Grenada                                      0
Holy See                                     0
Laos                                         0
Macau                                        0
Madagascar                                   0
Mongolia                                     0
Mozambique                                   0
Namibia                                      0
Nepal                                        0
Rwanda                                       0
Saint Kitts and Nevis                        0
Saint Lucia                                  0
Saint Vincent and the Grenadines             0
Seychelles                                   0
South Sudan                                  0
Timor-Leste                                  0
Uganda                                       0
Vietnam                                      0

### Question 4.5: India totals as of 29 April 2020

In [6]:
india = df[df['Region'].eq('India')]
print('Dates in India records:', india['Date'].unique().tolist())
display(india[['Confirmed','Deaths','Recovered']].sum().to_frame('India_total'))

Dates in India records: ['4/29/2020']

           India_total
Confirmed        33062
Deaths            1079
Recovered         8437

### Question 4.6A: Sort records by Confirmed ascending

In [7]:
confirmed_ascending = df.sort_values('Confirmed', ascending=True)
display(confirmed_ascending.head(12))

,Date,State,Region,Confirmed,Deaths,Recovered
70,4/29/2020,NaN,Holy See,10,0,2
59,4/29/2020,NaN,Gambia,10,1,8
156,4/29/2020,NaN,Suriname,10,1,8
27,4/29/2020,NaN,Burundi,11,1,4
217,4/29/2020,Greenland,Denmark,11,0,11
318,4/29/2020,Yukon,Canada,11,0,0
144,4/29/2020,NaN,Seychelles,11,0,6
256,4/29/2020,Montserrat,UK,11,1,2
306,4/29/2020,Turks and Caicos Islands,UK,12,1,5
206,4/29/2020,Falkland Islands (Malvinas),UK,13,0,11
215,4/29/2020,Grand Princess,Canada,13,0,0
118,4/29/2020,NaN,Nicaragua,13,3,7

### Question 4.6B: Sort records by Recovered descending

In [8]:
recovered_descending = df.sort_values('Recovered', ascending=False)
display(recovered_descending.head(12))

          Date  State          Region  Confirmed  Deaths  Recovered
153  4/29/2020    NaN           Spain     236899   24275     132929
61   4/29/2020    NaN         Germany     161539    6467     120400
76   4/29/2020    NaN            Iran      93657    5957      73791
80   4/29/2020    NaN           Italy     203591   27682      71252
229  4/29/2020  Hubei  Mainland China      68128    4512      63616
57   4/29/2020    NaN          France     165093   24087      48228
167  4/29/2020    NaN          Turkey     117589    3081      44040
22   4/29/2020    NaN          Brazil      79685    5513      34132
158  4/29/2020    NaN     Switzerland      29407    1716      22600
78   4/29/2020    NaN         Ireland      20253    1190      13386
8    4/29/2020    NaN         Austria      15402     580      12779
107  4/29/2020    NaN          Mexico      17799    1732      11423